name: Run Tests

on:
  push:
    branches: '**'
  pull_request:

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Web Tests
        working-directory: ./packages/web
        run: |
          npm i
          npm test
        continue-on-error: false
